#!/usr/bin/env python3
"""Generate traceable LaTeX tables for the V6 information-anchor evidence set."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
EVIDENCE = ROOT / "results/information_anchor_v6_evidence"
ROBUSTNESS = ROOT / "results/information_anchor_v6_robustness"
REGISTRY = ROOT / "configs/information_anchor/v6_registered/registry.json"
OUTPUT = ROOT / "results/information_anchor_v6_tables"

MODEL_ORDER = ("Chronos2", "Moirai2", "Toto2", "TimesFM2.5", "ChronosBolt", "TTM")
MODEL_LABELS = {
    "Chronos2": "Chronos-2",
    "Moirai2": "Moirai-2",
    "Toto2": "Toto-2",
    "TimesFM2.5": "TimesFM 2.5",
    "ChronosBolt": "Chronos-Bolt",
    "TTM": "TTM-R2",
}


def _write(name: str, content: str) -> None:
    """以稳定 UTF-8 编码写入单个可直接输入的 LaTeX 表格。"""
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / name).write_text(content.rstrip() + "\n", encoding="utf-8")


def _f(value: float, digits: int = 3) -> str:
    """统一格式化有限浮点数，避免正文与补充材料的精度不一致。"""
    return f"{float(value):.{digits}f}"


def _tex(value: str) -> str:
    """转义模型架构描述中的 LaTeX 特殊字符。"""
    return value.replace("&", r"\&").replace("_", r"\_")


def make_model_table(registry: dict) -> None:
    """生成模型异构性表，明确比较的是组织模式而非预测能力排名。"""
    rows = []
    for model in MODEL_ORDER:
        spec = registry["models"][model]
        rows.append(
            f"{MODEL_LABELS[model]} & {_tex(spec['compute_path'])} & "
            f"{_tex(spec['cross_channel_interaction'])} & {_tex(spec['analyzed_history_unit'])} \\\\"
        )
    _write(
        "table1_models.tex",
        r"""% Generated by scripts/information_anchor/make_v6_tables.py.
\begin{table*}[t]
\centering
\caption{Registered frozen TSFMs and native history units. The table describes analysis surfaces, not a performance ranking.}
\label{tab:models}
\small
\begin{tabular}{lp{0.11\textwidth}p{0.19\textwidth}p{0.34\textwidth}}
\toprule
Model & Compute path & Cross-channel mechanism & Analysed native history unit \\
\midrule
"""
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table*}
""",
    )


def make_topology_table() -> None:
    """生成跨数据集的归一化 topology 描述符总表，不暴露不可比 raw MI。"""
    table = pd.read_csv(EVIDENCE / "architecture_synthesis.csv").set_index("model")
    rows = []
    for model in MODEL_ORDER:
        row = table.loc[model]
        rows.append(
            f"{MODEL_LABELS[model]} & {_f(row.mean_top_quarter_concentration)} & "
            f"{_f(row.mean_anchor_ratio)} & {_f(row.mean_mean_boundary_distance)} & "
            f"{_f(row.mean_expected_layer_depth)} & {_f(row.mean_probe_top_minus_low_r2)} & "
            f"{_f(row.probe_top_above_low_fraction)} \\\\"
        )
    _write(
        "table2_topology.tex",
        r"""% Within-run normalized descriptors, averaged over the seven registered datasets.
\begin{table}[t]
\centering
\caption{Cross-dataset information topology and semantic accessibility. $Q_{0.25}$ is normalized top-quarter temporal concentration; $d_b$ is normalized distance from the forecast boundary. Raw MI is intentionally omitted because it is not comparable across architectures.}
\label{tab:topology}
\small
\begin{tabular}{lrrrrrr}
\toprule
Model & $Q_{0.25}$ & Anchor ratio & $d_b$ & Layer depth & $\Delta R^2_{\mathrm{probe}}$ & $P(\Delta R^2>0)$ \\
\midrule
"""
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
""",
    )


def make_semantic_table() -> None:
    """生成两种 probe 语义范围的组级读出表，保留难以线性读出的负 R2。"""
    data = pd.read_csv(EVIDENCE / "probe_semantic_groups.csv")
    groups = ("level", "trajectory", "local_dynamics", "frequency")
    labels = {
        "level": "Level",
        "trajectory": "Trajectory",
        "local_dynamics": "Local dynamics",
        "frequency": "Frequency",
    }
    rows = []
    for scope in ("global", "target"):
        for group in groups:
            subset = data[(data.scope == scope) & (data.semantic_group == group)]
            rows.append(
                f"{scope.capitalize()} & {labels[group]} & {_f(subset.functional_top_r2.mean())} & "
                f"{_f(subset.functional_low_r2.mean())} & {_f(subset.functional_top_minus_low_r2.mean())} \\\\"
            )
    _write(
        "table3_semantics.tex",
        r"""% Grouped semantic-probe results averaged across six models and seven datasets.
\begin{table}[t]
\centering
\caption{Held-out semantic accessibility at the functional-layer top-MI and low-MI patches. Negative chronological $R^2$ values are retained rather than clipped.}
\label{tab:semantics}
\small
\begin{tabular}{llrrr}
\toprule
Scope & Semantic group & Top-MI $R^2$ & Low-MI $R^2$ & Difference \\
\midrule
"""
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
""",
    )


def make_functional_table() -> None:
    """生成 ETTm1 的正式配对干预汇总，报告 25% 预算和准确的符号翻转检验。"""
    conditions = pd.read_csv(EVIDENCE / "progressive_conditions.csv")
    contrasts = pd.read_csv(EVIDENCE / "progressive_contrasts.csv")
    rows = []
    for model in MODEL_ORDER:
        top = conditions[
            (conditions.model == model)
            & (conditions.dataset_key == "ettm1")
            & (conditions["mode"] == "remove")
            & (conditions.strategy == "top")
            & (conditions.fraction == 0.25)
        ].iloc[0]
        sub = contrasts[
            (contrasts.model == model)
            & (contrasts.dataset_key == "ettm1")
            & (contrasts["mode"] == "remove")
            & (contrasts.fraction == 0.25)
        ]
        bottom = sub[sub.contrast == "top_minus_bottom"].iloc[0]
        random = sub[sub.contrast == "top_minus_random_mean"].iloc[0]
        interval_bottom = f"[{_f(bottom.all_forecast_change_mse_ci95_lower)}, {_f(bottom.all_forecast_change_mse_ci95_upper)}]"
        interval_random = f"[{_f(random.all_forecast_change_mse_ci95_lower)}, {_f(random.all_forecast_change_mse_ci95_upper)}]"
        rows.append(
            f"{MODEL_LABELS[model]} & {_f(top.all_forecast_change_mse_mean)} & "
            f"{_f(bottom.all_forecast_change_mse_mean)} {interval_bottom} & "
            f"{_f(random.all_forecast_change_mse_mean)} {interval_random} & "
            f"{_f(bottom.all_forecast_change_mse_sign_flip_p_greater, 4)} \\\\"
        )
    _write(
        "table4_functional_ettm1.tex",
        r"""% ETTm1 necessity test at 25% selected history patches.
\begin{table*}[t]
\centering
\caption{Matched donor-replacement necessity test on ETTm1 at 25\% selected patches. Values are all-variable forecast-change MSE. Brackets give paired hierarchical-bootstrap 95\% CIs for the top-MI contrast; $p$ is an exact donor-level one-sided sign-flip test.}
\label{tab:functional}
\small
\begin{tabular}{lrp{0.24\textwidth}p{0.24\textwidth}r}
\toprule
Model & Top-MI & Top $-$ bottom & Top $-$ random mean & $p_{\mathrm{top>bottom}}$ \\
\midrule
"""
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table*}
""",
    )


def make_robustness_tables() -> None:
    """生成长度、估计器与全变量压力测试的附录稳健性表。"""
    length = pd.read_csv(ROBUSTNESS / "length_robustness.csv")
    sensitivity = pd.read_csv(ROBUSTNESS / "estimator_sensitivity.csv")
    stress = pd.read_csv(ROBUSTNESS / "full_variable_stress.csv")

    length_rows = []
    for model in MODEL_ORDER:
        subset = length[length.model == model]
        if subset.empty:
            continue
        values = subset[["patch_profile_spearman", "layer_profile_spearman", "atlas_spearman"]].mean()
        length_rows.append(f"{MODEL_LABELS[model]} & {_f(values.iloc[0])} & {_f(values.iloc[1])} & {_f(values.iloc[2])} \\\\")
    _write(
        "tableA1_length_robustness.tex",
        r"""\begin{table}[t]
\centering
\caption{ETT-family robustness when moving from $(L,P)=(512,96)$ to $(336,192)$. Values are mean Spearman correlations across ETT datasets. TTM-R2 is omitted because its evaluated checkpoint requires the native $(512,96)$ context.}
\label{tab:length-robustness}
\small
\begin{tabular}{lrrr}
\toprule
Model & Patch profile & Layer profile & Full atlas \\
\midrule
"""
        + "\n".join(length_rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
""",
    )

    labels = {
        "k3": "$k=3$",
        "k10": "$k=10$",
        "pca4": "PCA=4",
        "pca16": "PCA=16",
        "null99": "99 nulls",
        "null399": "399 nulls",
    }
    sensitivity_rows = []
    for variant in ("k3", "k10", "pca4", "pca16", "null99", "null399"):
        values = sensitivity[sensitivity.variant == variant][["patch_profile_spearman", "layer_profile_spearman", "atlas_spearman"]].mean()
        sensitivity_rows.append(f"{labels[variant]} & {_f(values.iloc[0])} & {_f(values.iloc[1])} & {_f(values.iloc[2])} \\\\")
    _write(
        "tableA2_estimator_sensitivity.tex",
        r"""\begin{table}[t]
\centering
\caption{ETTm1 atlas robustness to one estimator change at a time, relative to the registered $k=5$, PCA=8, 199-null atlas. Values average six models.}
\label{tab:estimator-sensitivity}
\small
\begin{tabular}{lrrr}
\toprule
Variant & Patch profile & Layer profile & Full atlas \\
\midrule
"""
        + "\n".join(sensitivity_rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
""",
    )

    stress_rows = []
    for _, row in stress.iterrows():
        stress_rows.append(
            f"{MODEL_LABELS[row.model]} & {str(row.dataset).capitalize()} & {int(row.panel_channel_count)} / {int(row.full_channel_count)} & "
            f"{_f(row.patch_profile_spearman)} & {_f(row.layer_profile_spearman)} & {_f(row.atlas_spearman)} \\\\"
        )
    _write(
        "tableA3_full_variable_stress.tex",
        r"""\begin{table}[t]
\centering
\caption{Panel-to-full-variable stress test for scalable native context constructions. The registered 16-channel panel is compared with the full Electricity (321) or Traffic (862) context. This is a boundary test, not a replacement for the preregistered panel matrix.}
\label{tab:full-variable-stress}
\small
\begin{tabular}{llrrrr}
\toprule
Model & Dataset & Channels & Patch profile & Layer profile & Full atlas \\
\midrule
"""
        + "\n".join(stress_rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
""",
    )


def make_baseline_table() -> None:
    """生成干预运行对应的标准化基线误差表，仅用于量纲核对而非模型排名。"""
    baselines = pd.read_csv(EVIDENCE / "forecast_baselines.csv")
    rows = []
    for model in MODEL_ORDER:
        subset = baselines[baselines.model == model]
        values = subset[
            [
                "baseline_target_mse",
                "baseline_target_mae",
                "baseline_all_mse",
                "baseline_all_mae",
            ]
        ].mean()
        rows.append(
            f"{MODEL_LABELS[model]} & {len(subset)} & {_f(values.iloc[0])} & "
            f"{_f(values.iloc[1])} & {_f(values.iloc[2])} & {_f(values.iloc[3])} \\\\"
        )
    _write(
        "tableA4_intervention_baselines.tex",
        r"""\begin{table*}[t]
\centering
\caption{Train-standardized baseline errors for the completed formal intervention runs. Each value is a macro average over the listed model's covered data regimes; coverage is 7 for Chronos-2, Moirai-2, Toto-2, and TTM-R2, and ETTm1 only for TimesFM 2.5 and Chronos-Bolt. This is a metric-scale audit, not a cross-model forecasting benchmark.}
\label{tab:intervention-baselines}
\small
\begin{tabular}{lrrrrr}
\toprule
Model & Regimes & Target MSE & Target MAE & All-variable MSE & All-variable MAE \\
\midrule
"""
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table*}
""",
    )


def main() -> None:
    """从审计通过的摘要 CSV 再生全部主文和附录 LaTeX 表。"""
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    make_model_table(registry)
    make_topology_table()
    make_semantic_table()
    make_functional_table()
    make_robustness_tables()
    make_baseline_table()
    print(json.dumps({"status": "complete", "output_dir": str(OUTPUT)}))


if __name__ == "__main__":
    main()
